### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by MageFX** [poqdavid/VirtualTool#10]
Get a lily pad with a block under it and jump and set a home in the air and go to the home and you character will glitch out and keep opening the pack back and taking things out and it will dupe them.

- Report from player apparently old faction trick.

**Comment by poqdavid** [comment]
I will try to fix it don't worry

**Comment by poqdavid** [comment]
I will try to fix it don't worry

**Comment by poqdavid** [comment]
@MageFX check it on the 4.0 that i just released and let me know
