### ISSUE TITLE
Backpack locked?

### ISSUE THREAD

**Issue by OttoOttoman** [poqdavid/VirtualTool#11]
Hey my players are getting a backpack locked message when try to use there backpacks. We have switched to 1.12.1 and now receiving errors? Can you fix this please and thank you I hope you can this mod brings a lot of joy to players.

**Comment by poqdavid** [comment]
Well ofc you will get an error when u use the mod for 1.12.1 since it been built for 1.10.2, but don't worry I will add 1.12.1 and higher Minecraft versions I just need a bit more time since its a busy time for me

**Comment by poqdavid** [comment]
Also for the backpack lock, there is a command to unlock it

**Comment by OttoOttoman** [comment]
Oh in 1.12.2 backpacks don't work automatically lock and wont unlock.

**Comment by poqdavid** [comment]
yah because maybe it causes an error so it stays locked

**Comment by OttoOttoman** [comment]
When can you have a patch thats for 1.12.2 if you are going to update to it which I very much hope so?!

**Comment by poqdavid** [comment]
Well I can't give you a time but I will do it as soon as I can
