### ISSUE TITLE
Players Cant Do /Enderchest

### ISSUE THREAD

**Issue by SweggyDucks** [poqdavid/VirtualTool#12]
So I am trying to give players with Ho-Oh rank+ the permission to use /echest but I have gotten multiple reports of it not working. I am almost sure I put in the permission node correctly so I dont know whats wrong. Here is a pastebin of my permission setup for that rank: https://pastebin.com/3bP8Vid6

**Comment by poqdavid** [comment]
i am not sure why its not working unless you show me a error log but with nucleus you can disable enderchest from my plugin and use the one from nucleus

**Comment by SweggyDucks** [comment]
how do i disable enderchests from your plugin?

**Comment by poqdavid** [comment]
here https://github.com/poqdavid/VirtualTool#configuration using the config and make sure you reboot
