### ISSUE TITLE
Putting Items in Backpack, closing, then opening and they're gone

### ISSUE THREAD

**Issue by Adam413** [poqdavid/VirtualTool#15]
Happens to a few of our players. Basically, if you put any item into the Backpack and close the backpack, it will suddenly disappear. It seems to happen randomly and consistently with several players whereas others do not experience it.

Currently we're running 5.0. We downloaded this on April 6th of this year. I noticed there were several commits since then.

I also noticed on the Sponge website another user had the same issue. I'm wondering if the latest commits fixed this and if the build in the Releases section is up-to-date or if I need to build from Source. Is it also safe to change the versions? 

Thanks!

**Comment by poqdavid** [comment]
The current version of the backpack is working fine on http://www.pocketpixels.net/ but that's on 1.12.2

**Comment by Adam413** [comment]
Right! Sorry, I completely forgot to list the branch we're on.

Our live server is running 1.12.2 on Forge build 2611 and Sponge build 2990 API 7.1.0.

We have version 5.0 of your plugin downloaded April 6th.

The issue isn't 100% server-killing, it happens to I'd say about 100 players out of about 15,000, but it primarily happens to our highest donators who have the highest setting level of backpacks, 6. It doesn't seem to happen to the Ender Chests. I've personally experienced it with the lowest setting as well.

If there's a log or if I need to enable debugging please let me know.

**Comment by poqdavid** [comment]
I would suggest trying SpongeForge [1.12.2-2705-7.1.0-BETA-3361](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2705-7.1.0-BETA-3361/spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar) then see if it will fix anything

**Comment by poqdavid** [comment]
I would suggest to use SpongeForge [1.12.2-2705-7.1.0-BETA-3361](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2705-7.1.0-BETA-3361/spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar) then see if it will fix anything
