### ISSUE TITLE
Backpack locks itself without reason

### ISSUE THREAD

**Issue by EscolarProgramming** [poqdavid/VirtualTool#18]
If you open your backpack, close it and open it again it is locked - every time.

We're running on: 
VirtualTool 5.0
SF 2768 RC 3594

The problem occured after updating Pixelmon from 7.0.1 to 7.0.3 (I don't think it's related to that issue) and updating SF from RC 3575 to RC 3594

**Comment by Shiunin** [comment]
Same issue, occurred right after updating SF to 3593

**Comment by HeyWinkeyFace** [comment]
Same Issue!

**Comment by poqdavid** [comment]
yah no worries

**Comment by UselessBen413** [comment]
Also having this issue right after updating to SF 3604

**Comment by poqdavid** [comment]
oh right i already fixed it will commit to the repo and make a release soon

**Comment by poqdavid** [comment]
fixed
