### ISSUE TITLE
Secondary development

### ISSUE THREAD

**Issue by mcqwy** [poqdavid/VirtualTool#20]
Hello!
Look, you haven't updated it for a long time.
Can I use the source code of your plug-in for secondary development and release it to other forums?
I will provide the link of the original plug-in and your name on the forum!

**Comment by poqdavid** [comment]
you want me to update it? like what sort of update?

**Comment by poqdavid** [comment]
Not really if you want it to be released to other places u can just ask me

**Comment by mcqwy** [comment]
Hello, can you make it support MySQL?
Thank you very much if you can.

**Comment by mcqwy** [comment]
Hello!
Can I move this plug-in to China's mcbss?
Mcbbs is the largest forum in China
If possible, I will provide the original link of the plug-in and your name.

**Comment by poqdavid** [comment]
for that you can just make a topic and like the link to my github 
and for MySQL i will add it to my todo list

**Comment by mcqwy** [comment]
Well, thank you very much

**Comment by poqdavid** [comment]
No problem I will close this for now once I add it will let you know.
