### ISSUE TITLE
Creating file errors

### ISSUE THREAD

**Issue by WinggedPhantom** [poqdavid/VirtualTool#3]
Errors on load and errors when trying to create backpack files for player:
https://pastebin.com/BtQ8riBC

**Comment by poqdavid** [comment]
Thanks I will look in to it, also you had old .json files correct?

**Comment by WinggedPhantom** [comment]
No, this is with a fresh install of the plugin with nothing else other than sponge.

**Comment by poqdavid** [comment]
Ok don't worry I am fixing the problems

**Comment by poqdavid** [comment]
Ok please try the new version and tell me if its fixed
