### ISSUE TITLE
Backpack locking error.

### ISSUE THREAD

**Issue by NyoxMMO** [poqdavid/VirtualTool#4]
So here, I'm trying to open one of my players' locked backpack. Here's what it shows in-game https://gyazo.com/7cb999ff4338584afbaa4e05135558d4 and then here's what showed up in my console https://pastebin.com/B36Ukdsx Hope this helps.

**Comment by poqdavid** [comment]
Thanks I will work on it and once I made sure it works fine I will make a release, is it possible for you to give me the bp file

**Comment by poqdavid** [comment]
I made the changes please check if its fixed

**Comment by NyoxMMO** [comment]
Yep! Backpacks with the error were unlocked when that version was put on. I'll keep an eye on things in case something goes wrong but looks like you fixed it! Thank you and good job.

**Comment by poqdavid** [comment]
Thanks and Your welcome
